### ISSUE TITLE
Modify squirrel asset to include night vision goggles

### ISSUE THREAD

**Issue by caractus** [caractus-org/illustrations#2]
### Context and Problem

This boring squirrel _MUST_ be modified to include night vision goggles.

![squirrel@4x](https://user-images.githubusercontent.com/4284843/169301090-508eb884-c2ad-44b7-8233-eb489aab8fb7.png)
### Acceptance Criteria

- _MUST_ use four tube 'Ground Panoramic' style night vision goggles similar to those pictured below

![products-GPNVG18_BNVS_af](https://user-images.githubusercontent.com/4284843/169301194-32a46b9e-e2cc-4662-ab7f-a28699b74ec8.jpeg)

**Comment by TreeLogger** [comment]
![night squirrel](https://user-images.githubusercontent.com/105868625/169389325-639519f5-9c5c-426e-a142-22c9c7ad89ff.jpg)

**Comment by DevotoBTC** [comment]
![Modify squirrel asset to include night vision goggles](https://user-images.githubusercontent.com/105864753/169407024-5b0d537d-7764-4e31-8cf2-66c4ea336b84.png)

**Comment by caractus** [comment]
These submissions have been accepted and this bounty is no longer available.
